In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_json('/content/sample_data/anscombe.json')
df.head()

,Series,X,Y
0,I,10,8.04
1,I,8,6.95
2,I,13,7.58
3,I,9,8.81
4,I,11,8.33


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Series  44 non-null     object 
 1   X       44 non-null     int64  
 2   Y       44 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ KB


In [9]:
df.dropna(how='any',inplace=True)
df.head()

,Series,X,Y
0,I,10,8.04
1,I,8,6.95
2,I,13,7.58
3,I,9,8.81
4,I,11,8.33


In [10]:
df["X"].value_counts()//len(df)*100

,count
X,
8,0
10,0
13,0
9,0
11,0
14,0
6,0
4,0
12,0


In [11]:
x=df.drop(['X','Y'],axis=1)
x.head()

,Series
0,I
1,I
2,I
3,I
4,I


In [12]:
y=df.X.values
y

array([10,  8, 13,  9, 11, 14,  6,  4, 12,  7,  5, 10,  8, 13,  9, 11, 14,
        6,  4, 12,  7,  5, 10,  8, 13,  9, 11, 14,  6,  4, 12,  7,  5,  8,
        8,  8,  8,  8,  8,  8, 19,  8,  8,  8])

In [13]:

x.columns


Index(['Series'], dtype='object')

In [14]:
x=df.drop(['X','Y'],axis=1)
x=pd.get_dummies(x,columns=['Series'],drop_first=True)
x.head()

,Series_II,Series_III,Series_IV
0,False,False,False
1,False,False,False
2,False,False,False
3,False,False,False
4,False,False,False


In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
len(x_train),len(x_test),len(y_train),len(y_test)

(35, 9, 35, 9)

***feature sealing***

In [17]:
from sklearn.preprocessing import StandardScaler as standardScaler
sc=standardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [18]:
x_train

array([[-0.63245553,  2.        , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [ 1.58113883, -0.5       , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       , -0.588

In [19]:
!pip install matplotlib-venn

In [39]:
!apt-get -qq install -y libfluidsynth1

E: Package 'libfluidsynth1' has no installation candidate


In [40]:
# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

Selecting previously unselected package libarchive-dev:amd64.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../libarchive-dev_3.6.0-1ubuntu1.7_amd64.deb ...
Unpacking libarchive-dev:amd64 (3.6.0-1ubuntu1.7) ...
Setting up libarchive-dev:amd64 (3.6.0-1ubuntu1.7) ...
Processing triggers for man-db (2.10.2-1) ...
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 6.6 MB/s eta 0:00:00
  Created wheel for libarchive: filename=libarchive-0.4.7-py3-none-any.whl size=31629 sha256=2db5a52e26490050940d6b94b8df186afa3a001daacefb80b8b663a5534ea121
  Stored in directory: /root/.cache/pip/wheels/29/20/ab/f101da7b245b996aa097685ef742243725ea6150f5b3b6d9ed
Successfully built libarchive


In [41]:
# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

In [42]:
!pip install cartopy
import cartopy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 60.3 MB/s eta 0:00:00


In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
model=KNeighborsClassifier()

In [45]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [46]:
y_pred=model.predict(x_test)
y_pred

array([4, 8, 4, 4, 4, 4, 4, 4, 8])

In [47]:
y_test

array([12,  8, 14, 11,  5,  9,  6, 10,  8])

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

22.22222222222222

In [49]:
x_test[:]

array([[-0.63245553,  2.        , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553,  2.        , -0.58834841],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317]])

In [50]:
data=[[0,2,89,178,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0]]

In [51]:
data_sc = sc.transform(data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


ValueError: X has 23 features, but StandardScaler is expecting 3 features as input.

In [52]:
single=model.predict(data_sc)
print(single)

[4]


In [53]:
from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier()
model1.fit(x_train,y_train)

DecisionTreeClassifier()

In [54]:
y_pred1=model1.predict(x_test)
print(y_pred1)
print(y_test)

[4 8 4 4 4 4 4 4 8]
[12  8 14 11  5  9  6 10  8]


In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)*100

22.22222222222222

In [56]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(x_train,y_train)

RandomForestClassifier()

In [57]:
y_pred2=model2.predict(x_test)
print(y_pred2)
print(y_test)

[7 8 7 6 6 7 7 7 8]
[12  8 14 11  5  9  6 10  8]


In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)*100

22.22222222222222

In [59]:
def calculat_gini(df_label):
    classes, class_counts = np.unique(df_label, return_counts=True)
    probabilities = class_counts / len(df_label)
    entropy_value = -np.sum(probabilities * np.log2(probabilities))
    print(entropy_value)

In [61]:
calculat_gini(y)

3.285463633240277


In [62]:
def calculate_entropy1(labels):
    _, counts = np.unique(labels, return_counts=True)
    probabilities = counts / counts.sum()

    return -np.sum(probabilities * np.log2(probabilities))


In [63]:
calculate_entropy1(x)

np.float64(0.8112781244591328)

In [64]:
from sklearn.ensemble import AdaBoostClassifier
model3=AdaBoostClassifier(n_estimators=100)
model3.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=100)

In [65]:
y_pred3=model3.predict(x_test)


In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred3)*100

22.22222222222222

In [1]:
!pip install catboost
from catboost import CatBoostClassifier


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.6 MB/s eta 0:00:00


In [30]:
q=CatBoostClassifier()
q.fit(x_train,y_train)

Learning rate set to 0.066692
0:	learn: 2.4519501	total: 46.2ms	remaining: 46.1s
1:	learn: 2.4206527	total: 46.4ms	remaining: 23.1s
2:	learn: 2.3909493	total: 46.5ms	remaining: 15.5s
3:	learn: 2.3635038	total: 46.6ms	remaining: 11.6s
4:	learn: 2.3375375	total: 46.7ms	remaining: 9.3s
5:	learn: 2.3124163	total: 46.9ms	remaining: 7.77s
6:	learn: 2.2894832	total: 47ms	remaining: 6.67s
7:	learn: 2.2721123	total: 47.1ms	remaining: 5.84s
8:	learn: 2.2516412	total: 47.2ms	remaining: 5.2s
9:	learn: 2.2316172	total: 47.3ms	remaining: 4.68s
10:	learn: 2.2151766	total: 47.4ms	remaining: 4.26s
11:	learn: 2.1972335	total: 47.6ms	remaining: 3.92s
12:	learn: 2.1803366	total: 47.8ms	remaining: 3.63s
13:	learn: 2.1644926	total: 47.9ms	remaining: 3.37s
14:	learn: 2.1494847	total: 48ms	remaining: 3.15s
15:	learn: 2.1353283	total: 48.2ms	remaining: 2.96s
16:	learn: 2.1220566	total: 48.3ms	remaining: 2.79s
17:	learn: 2.1100416	total: 48.4ms	remaining: 2.64s
18:	learn: 2.0980910	total: 48.6ms	remaining: 2.51

CatBoostClassifier()

In [34]:
y_pred4=q.predict(x_test)
y_pred4

array([[8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8]])

In [78]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
model5=XGBClassifier()
model5.fit(x_train, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [79]:
y_pred5=model5.predict(x_test)
y_pred5

array([6, 4, 6, 4, 4, 6, 6, 4, 4])

In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred5)*100

11.11111111111111

In [81]:
from sklearn.ensemble import GradientBoostingClassifier
model6=GradientBoostingClassifier()
model6.fit(x_train,y_train)


GradientBoostingClassifier()

In [82]:
y_pred6=model6.predict(x_test)
y_pred6

array([8, 8, 8, 8, 8, 8, 8, 8, 8])

In [83]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred6)*100

22.22222222222222